// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzoywzz8EcGTIO2ca9uTZu5NDZtj40qHM',
    appId: '1:1015792581188:web:39ecb49c077e9be0e55a11',
    messagingSenderId: '1015792581188',
    projectId: 'roomie-529d3',
    authDomain: 'roomie-529d3.firebaseapp.com',
    storageBucket: 'roomie-529d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB817o7SbzOOtAHEGy-f5qDoS4YUjL-EoA',
    appId: '1:1015792581188:android:5441b37cb8aa4baae55a11',
    messagingSenderId: '1015792581188',
    projectId: 'roomie-529d3',
    storageBucket: 'roomie-529d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpkvXDDVVr9Gkf4qJHImkVd2eswJ2kwXA',
    appId: '1:1015792581188:ios:562848c541fc37f9e55a11',
    messagingSenderId: '1015792581188',
    projectId: 'roomie-529d3',
    storageBucket: 'roomie-529d3.appspot.com',
    iosBundleId: 'com.akash.roomie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpkvXDDVVr9Gkf4qJHImkVd2eswJ2kwXA',
    appId: '1:1015792581188:ios:fbabebc821200a8ee55a11',
    messagingSenderId: '1015792581188',
    projectId: 'roomie-529d3',
    storageBucket: 'roomie-529d3.appspot.com',
    iosBundleId: 'com.example.roomie.RunnerTests',
  );
}
